apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: distribution
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: "dockercloud/hello-world"
          imagePullPolicy: Always
          name: hello-world-container
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: distribution
spec:
  ports:
     -  port: 8080
        protocol: TCP
        targetPort: 8080
  selector:
    app: hello-world
  type: NodePort
